"""
Automatic PDF Report
Pulls together district ranking, ML forecast, what-if scenarios, and an LLM
executive summary into one professional PDF report.

Run:
    python modules/pdf_report.py
"""

import sys
import os
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from modules.district_ranking import rank_districts, explain_ranking
from modules.what_if_analysis import build_default_scenarios, compare_scenarios
from modules.llm_client import chat


def build_report(out_path=os.path.join(config.OUTPUT_DIR, "EV_Policy_Report.pdf")):
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    os.makedirs(config.SCENARIO_DIR, exist_ok=True)

    # ---- gather data ----
    ranked = rank_districts()
    ranking_explanation = explain_ranking(ranked)

    if not os.listdir(config.SCENARIO_DIR):
        build_default_scenarios()
    scenarios_df = compare_scenarios()

    exec_summary = chat(
        f"Top districts by EV readiness:\n{ranked.head(5).to_string(index=False)}\n\n"
        f"Scenario comparison:\n{scenarios_df.to_string(index=False)}\n\n"
        "Write a 4-5 sentence executive summary for a Karnataka government EV policy report, "
        "aimed at a transport department secretary.",
        system="You are drafting the executive summary of an official government policy report.",
    )

    # ---- build PDF ----
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=20)
    h2 = styles["Heading2"]
    body = styles["Normal"]

    doc = SimpleDocTemplate(out_path, pagesize=letter,
                             topMargin=0.7 * inch, bottomMargin=0.7 * inch)
    story = []

    story.append(Paragraph("Karnataka EV Policy Decision Support Report", title_style))
    story.append(Paragraph(datetime.date.today().strftime("Generated on %d %B %Y"), body))
    story.append(Spacer(1, 16))

    story.append(Paragraph("Executive Summary", h2))
    story.append(Paragraph(exec_summary.replace("\n", "<br/>"), body))
    story.append(Spacer(1, 16))

    story.append(Paragraph("District EV Readiness Ranking", h2))
    table_data = [list(ranked.columns)] + ranked.head(10).astype(str).values.tolist()
    t = Table(table_data, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))
    story.append(Paragraph(ranking_explanation.replace("\n", "<br/>"), body))

    story.append(PageBreak())
    story.append(Paragraph("What-If Scenario Comparison", h2))
    sc_data = [["Scenario", "Changes", "Predicted EV Adoption %"]]
    for _, row in scenarios_df.iterrows():
        sc_data.append([row["scenario"], str(row["changes"]), f"{row['predicted_ev_adoption_pct']:.2f}"])
    t2 = Table(sc_data, repeatRows=1, colWidths=[1.6 * inch, 3.2 * inch, 1.6 * inch])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(t2)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report was auto-generated by an AI-assisted policy decision support system "
        "combining machine learning forecasts, retrieval-augmented generation over official "
        "policy documents, and LLM-based natural language explanation.", styles["Italic"]
    ))

    doc.build(story)
    print(f"Report saved to {out_path}")
    return out_path


if __name__ == "__main__":
    build_report()
